services:
  - type: web
    name: timeskings
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install --omit=dev
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
    maxShutdownDelaySeconds: 30
    envVars:
      - key: NODE_ENV
        value: production
